server:
  port: 6080

eureka:
  instance:
    hostname: inst2
  client:
    serviceUrl:
      defaultZone: http://inst1:6000/eureka/

spring:
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/inst02
      username: root
      user: root
      password: 123456
      type: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
