server:
  port: 6070

eureka:
  instance:
    hostname: inst1
  client:
    serviceUrl:
      defaultZone: http://inst1:6000/eureka/

spring:
  datasource:
    primary:
      url: jdbc:mysql://127.0.0.1:3306/inst01
      username: root
      password: 123456
      type: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
